stages:
  process:
    cmd: python process_data.py
    deps:
    - process_data.py
    - rawdata_new_rev.csv
    outs:
    - data_processed.csv
  Train:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cashe:false
